# NOTA: para laboratorio usamos stringData en texto plano dentro del repo.
# En un entorno real NUNCA se comitea un Secret así -> más adelante añadimos
# Sealed Secrets o External Secrets Operator (integrable con Azure Key Vault).
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: k8s-demo
type: Opaque
stringData:
  POSTGRES_USER: tasksuser
  POSTGRES_PASSWORD: "CambiaEstaClave123!"
  POSTGRES_DB: tasksdb
  DB_USER: tasksuser
  DB_PASSWORD: "CambiaEstaClave123!"
