apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-api
  namespace: k8s-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tasks-api
  template:
    metadata:
      labels:
        app: tasks-api
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "tasks-api"
        vault.hashicorp.com/agent-inject-secret-db.env: "secret/data/tasks-api/db"
        vault.hashicorp.com/agent-inject-template-db.env: |
          {{- with secret "secret/data/tasks-api/db" -}}
          {{- range $k, $v := .Data.data }}
          export {{ $k }}={{ $v }}
          {{- end }}
          {{- end }}
    spec:
      containers:
        - name: tasks-api
          image: ghcr.io/cristianespinosa9/tasks-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: app-config
          readinessProbe:
            httpGet:
              path: /ready
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
