apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-web
  namespace: k8s-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks-web
  template:
    metadata:
      labels:
        app: tasks-web
    spec:
      containers:
        - name: tasks-web
          image: tasks-web:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 15
          resources:
            requests:
              cpu: "50m"
              memory: "32Mi"
            limits:
              cpu: "150m"
              memory: "64Mi"
